import Clothimage from "../assets/Clothimage.jpeg";
import fastrackwatch from "../assets/fastrackwatch.jpeg";
import NIkeshoes from "../assets/NIkeshoes.avif";
import dell from "../assets/dell.avif";
import iphone from "../assets/iphone.jpeg";
import bellavita from "../assets/bellavita.jpeg";
import sonytv from "../assets/sonytv.jpeg";
import boatearbuds from "../assets/boatearbuds.jpeg";
import lakme from "../assets/lakme.png";
import protienpowder from "../assets/protienpowder.jpeg";
const CardData = [
  {
    id: "1",
    brand: "Manyavar",
    rating: "4.5",
    productName: "Sherwani set",
    category: "clothes",
    productDescription: " Men Traditional Indo-Western Sherwani Set",
    img: Clothimage,
    price: 199,
    qnty: 0,
  },
  {
    id: "2",
    brand: "Nike",
    rating: "4.2",
    productName: "Nike Shoes",
    category: "shoes",
    productDescription: "Revolution 6 Running Shoes For Men",
    img: NIkeshoes,
    price: 99,
    qnty: 0,
  },
  {
    id: "3",
    brand: "Fastrack",
    rating: "3.8",
    productName: "fastrack Watch",
    category: "watches",
    productDescription: " Men Brass Dial & Steel Straps Analogue Watch",
    img: fastrackwatch,
    price: 299,
    qnty: 0,
  },
  {
    id: "4",
    brand: "iPhone 16 Pro",
    rating: "4.0",
    productName: "iPhone 16 Pro",
    category: "mobiles",
    productDescription: "Iphone pro Black Titanium",
    img: iphone,
    price: 4999,
    qnty: 0,
  },
  {
    id: "5",
    brand: "iPhone 15 Pro",
    rating: "4.0",
    productName: "iPhone 15 Pro",
    category: "mobiles",
    productDescription: "Iphone pro Black Titanium",
    img: iphone,
    price: 2999,
    qnty: 0,
  },
  {
    id: "6",
    brand: "iPhone 13 Pro",
    rating: "4.0",
    productName: "iPhone 13 Pro",
    category: "mobiles",
    productDescription: "Iphone pro Black Titanium",
    img: iphone,
    price: 1999,
    qnty: 0,
  },
  {
    id: "7",
    brand: "iPhone 16 Pro Max",
    rating: "4.0",
    productName: "iPhone 16 Pro Max",
    category: "mobiles",
    productDescription: "Iphone pro Black Titanium",
    img: iphone,
    price: 5999,
    qnty: 0,
  },
  {
    id: "8",
    brand: "Bellavita",
    rating: "3.5",
    productName: "Bellavita Perfume",
    category: "perfumes",
    productDescription: "Bella Vita Fresh Unisex Perfume, 100 ml",
    img: bellavita,
    price: 59,
    qnty: 0,
  },
  {
    id: "9",
    brand: "Sony TV",
    rating: "4.8",
    productName: "Sony TV",
    category: "tv",
    productDescription: "BRAVIA TV W830K | HDR TV | Smart TV | Sony India",
    img: sonytv,
    price: 1999,
    qnty: 0,
  },
  {
    id: "10",
    brand: "Lakme",
    rating: "4.5",
    productName: "Lakme Lipstick",
    category: "beauty",
    productDescription: "Lakme Glitter Collection Shine Lipstick - 3.4g",
    img: lakme,
    price: 499,
    qnty: 0,
  },
  {
    id: "11",
    brand: "Dell",
    rating: "4.6",
    productName: "Dell Laptop",
    category: "laptop",
    productDescription:
      "Dell Inspiron 15 15.6-inch 11th Gen Intel Core i5 Laptop",
    img: dell,
    price: 2999,
    qnty: 0,
  },
  {
    id: "12",
    brand: "Boat",
    rating: "4.5",
    productName: "Boat Earbuds",
    category: "earphones",
    productDescription:
      "Wireless Earbuds with upto 60 Hours Playback, 13mm Drivers, IWP Technology, 650mAh Charging Case",
    img: boatearbuds,
    price: 159,
    qnty: 0,
  },
  {
    id: "13",
    brand: "Myprotein",
    rating: "4.5",
    productDescription:
      "Myprotein Impact Whey Protein Blend, Cookies & Cream, 5.5 lbs 100 Servings",
    img: protienpowder,
    price: 699,
    qnty: 0,
  },
  {
    id: "14",
    brand: "iPhone 12 Pro",
    rating: "4.0",
    productName: "iPhone 12 Pro",
    category: "mobiles",
    productDescription: "Iphone pro Black Titanium",
    img: iphone,
    price: 599,
    qnty: 0,
  },
];

export default CardData;
